---
login:
  method: POST
  path: "/login"
  user_id: uuid
  status: '301'
  authentication:
    key: 'user.email'
    password: 'user.password'
events:
  $login.failed:
    status: '302'
    method: POST
    path: !ruby/regexp '/\/sign_in\/new/i'
    properties:
      email: user.email
  $logout.succeeded:
    status: '302'
    method: DELETE
    path: "/logout"
