---
identify:
  id: uuid
user_traits:
  registered_at: created_at
  email: email
  name: full_name
events:
  $login.succeeded:
    authenticate: true
    challenge: true
    method: POST
    path: "/login"
    status: '302'
    properties:
      email: 'user.email'
      password: 'user.password'
  $login.failed:
    status: '302'
    method: POST
    path: !ruby/regexp '/\/sign_in\/new/i'
    properties:
      email: user.email
  $logout.succeeded:
    status: '302'
    method: DELETE
    path: "/logout"
